name: Deploy Data Factory

on:
  push:
    branches:
      - master
      - adf_publish
  pull_request:
    branches:
      - master
      - adf_publish

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging]

    steps:
    - name: Checkout repository (main branch)
      uses: actions/checkout@v2

    - name: Checkout repository (adf_publish)
      uses: actions/checkout@v2
      with:
        ref: adf_publish
        path: ./

    - name: Set environment variables
      run: |
        echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV
        if [ "${{ matrix.environment }}" == "development" ]; then
          echo "RESOURCE_GROUP=rg-pgalvez" >> $GITHUB_ENV
          echo "DATA_FACTORY=adf-test-data1000" >> $GITHUB_ENV
        elif [ "${{ matrix.environment }}" == "staging" ]; then
          echo "RESOURCE_GROUP=rg-pgalvez" >> $GITHUB_ENV
          echo "DATA_FACTORY=adf-test-data2000" >> $GITHUB_ENV
        elif [ "${{ matrix.environment }}" == "production" ]; then
          echo "RESOURCE_GROUP=rg-pgalvez" >> $GITHUB_ENV
          echo "DATA_FACTORY=prod-data-factory" >> $GITHUB_ENV
        fi

    - name: Deploy Azure Data Factory
      uses: ./data-factory-deploy-action/
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        dataFactoryName: ${{ env.DATA_FACTORY }}
        armTemplateFile: './adf_publish/adf-test-data1000/ARMTemplateForFactory.json'
        armTemplateParametersFile: './adf_publish/adf-test-data1000/ARMTemplateParametersForFactory.json'
        additionalParameters: ''
        skipAzModuleInstallation: 'false'