name: Deploy Data Factory

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [development, staging, production]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set environment variables
      run: |
        echo "ENVIRONMENT=${{ matrix.environment }}" >> $GITHUB_ENV
        if [ "${{ matrix.environment }}" == "development" ]; then
          echo "RESOURCE_GROUP=rg-pgalvez" >> $GITHUB_ENV
          echo "DATA_FACTORY=adf-test-data1000" >> $GITHUB_ENV
        elif [ "${{ matrix.environment }}" == "staging" ]; then
          echo "RESOURCE_GROUP=rg-pgalvez" >> $GITHUB_ENV
          echo "DATA_FACTORY=staging-data-factory" >> $GITHUB_ENV
        elif [ "${{ matrix.environment }}" == "production" ]; then
          echo "RESOURCE_GROUP=rg-pgalvez" >> $GITHUB_ENV
          echo "DATA_FACTORY=prod-data-factory" >> $GITHUB_ENV
        fi

    - name: Deploy Azure Data Factory
      uses: ./
      with:
        resourceGroupName: ${{ env.RESOURCE_GROUP }}
        dataFactoryName: ${{ env.DATA_FACTORY }}
        armTemplateFile: 'ARMTemplateForFactory.json'
        armTemplateParametersFile: 'ARMTemplateParametersForFactory.json'
        additionalParameters: ''
        skipAzModuleInstallation: 'false'